Algoritmo "Entrada e saida de dados"

Var
// Seção de Declarações das variáveis 
 nome: caractere
 nota1, nota2, media: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite seu nome:")
 leia(nome)
 
 escreval("Digite sua primeira nota:")
 leia(nota1)
 
 escreval("Digite sua segunda nota:")
 leia(nota2)
 
 media <- (nota1 + nota2) \ 2
 
 escreval("Nome: ", nome)
 escreval("Sua média foi: ", media)
  
Fimalgoritmo