Algoritmo "estrutura para-faça"
Var
// Seção de Declarações das variáveis 
 numero, resultado, contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o numero para fatoração: ")
 leia(numero)
 resultado <- 1
 
 para contador de 1 ate numero faca
      resultado <- resultado * contador
 fimpara
 escreval("O fatorial de ", numero, " é: ", resultado)

Fimalgoritmo